version: "3.3"

services:
  spark-recording-sorting:
    image: spark:3.0.0
    container_name: "spark-recording-sorting"
    ports:
      - "4042:4040"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${VOLUMES_PATH}/spark/conf:/opt/spark-3.0.0-bin-hadoop3.2/conf
      - ${VOLUMES_PATH}/spark/logs:/opt/spark-3.0.0-bin-hadoop3.2/logs
      - ./jars:/opt/jars        
      - ./appJars:/opt/data-loader
    command: "bin/spark-submit --class com.ipm.nslab.bdns.Sorter --master spark://spark-master:7077 --executor-memory ${SPARK_EXECUTOR_MEMORY}G --total-executor-cores ${SPARK_EXECUTOR_CORES} --driver-memory ${SPARK_DRIVER_MEMORY}G /opt/data-loader/bdns-2.0.0.jar mongodb://root:ns123@mongos:27017/admin ${NAME}"
    networks:
      - spark-net

networks:
  spark-net:
    external:
     name: spark-net

